#!/bin/bash

set -e

echo "======================================"
echo " Kubernetes Worker Installation"
echo "======================================"

# -----------------------------
# 1. Update system
# -----------------------------
apt-get update -y
apt-get upgrade -y

# -----------------------------
# 2. Disable swap
# -----------------------------
swapoff -a
sed -i '/ swap / s/^/#/' /etc/fstab

# -----------------------------
# 3. Kernel modules
# -----------------------------
cat <<EOF > /etc/modules-load.d/k8s.conf
overlay
br_netfilter
EOF

modprobe overlay
modprobe br_netfilter

# -----------------------------
# 4. Kubernetes networking
# -----------------------------
cat <<EOF > /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-iptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward = 1
EOF

sysctl --system

# -----------------------------
# 5. Install containerd
# -----------------------------
apt-get install -y containerd

mkdir -p /etc/containerd

containerd config default > /etc/containerd/config.toml

sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' \
    /etc/containerd/config.toml

systemctl restart containerd
systemctl enable containerd

# -----------------------------
# 6. Install Kubernetes repository
# -----------------------------
apt-get install -y ca-certificates curl gpg

install -m 0755 -d /etc/apt/keyrings

curl -fsSL \
https://pkgs.k8s.io/core:/stable:/v1.34/deb/Release.key \
| gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.34/deb/ /' \
> /etc/apt/sources.list.d/kubernetes.list

apt-get update -y

# -----------------------------
# 7. Install Kubernetes
# -----------------------------
apt-get install -y kubelet kubeadm kubectl

apt-mark hold kubelet kubeadm kubectl

systemctl enable kubelet

echo ""
echo "======================================"
echo " Worker preparation completed"
echo "======================================"
echo ""
echo "Now run the kubeadm join command"
echo "generated by the MASTER EC2."
echo ""
